# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mixfa/json_c_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mixfa/json_c_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mixfa/json_c_test/CMakeFiles /home/mixfa/json_c_test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mixfa/json_c_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named json_c_test

# Build rule for target.
json_c_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json_c_test
.PHONY : json_c_test

# fast build rule for target.
json_c_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/build
.PHONY : json_c_test/fast

src/chat-socket/array_list_utils.o: src/chat-socket/array_list_utils.c.o
.PHONY : src/chat-socket/array_list_utils.o

# target to build an object file
src/chat-socket/array_list_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/array_list_utils.c.o
.PHONY : src/chat-socket/array_list_utils.c.o

src/chat-socket/array_list_utils.i: src/chat-socket/array_list_utils.c.i
.PHONY : src/chat-socket/array_list_utils.i

# target to preprocess a source file
src/chat-socket/array_list_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/array_list_utils.c.i
.PHONY : src/chat-socket/array_list_utils.c.i

src/chat-socket/array_list_utils.s: src/chat-socket/array_list_utils.c.s
.PHONY : src/chat-socket/array_list_utils.s

# target to generate assembly for a file
src/chat-socket/array_list_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/array_list_utils.c.s
.PHONY : src/chat-socket/array_list_utils.c.s

src/chat-socket/chat_socket.o: src/chat-socket/chat_socket.c.o
.PHONY : src/chat-socket/chat_socket.o

# target to build an object file
src/chat-socket/chat_socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/chat_socket.c.o
.PHONY : src/chat-socket/chat_socket.c.o

src/chat-socket/chat_socket.i: src/chat-socket/chat_socket.c.i
.PHONY : src/chat-socket/chat_socket.i

# target to preprocess a source file
src/chat-socket/chat_socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/chat_socket.c.i
.PHONY : src/chat-socket/chat_socket.c.i

src/chat-socket/chat_socket.s: src/chat-socket/chat_socket.c.s
.PHONY : src/chat-socket/chat_socket.s

# target to generate assembly for a file
src/chat-socket/chat_socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/chat_socket.c.s
.PHONY : src/chat-socket/chat_socket.c.s

src/chat-socket/requests.o: src/chat-socket/requests.c.o
.PHONY : src/chat-socket/requests.o

# target to build an object file
src/chat-socket/requests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/requests.c.o
.PHONY : src/chat-socket/requests.c.o

src/chat-socket/requests.i: src/chat-socket/requests.c.i
.PHONY : src/chat-socket/requests.i

# target to preprocess a source file
src/chat-socket/requests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/requests.c.i
.PHONY : src/chat-socket/requests.c.i

src/chat-socket/requests.s: src/chat-socket/requests.c.s
.PHONY : src/chat-socket/requests.s

# target to generate assembly for a file
src/chat-socket/requests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/requests.c.s
.PHONY : src/chat-socket/requests.c.s

src/chat-socket/responses.o: src/chat-socket/responses.c.o
.PHONY : src/chat-socket/responses.o

# target to build an object file
src/chat-socket/responses.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/responses.c.o
.PHONY : src/chat-socket/responses.c.o

src/chat-socket/responses.i: src/chat-socket/responses.c.i
.PHONY : src/chat-socket/responses.i

# target to preprocess a source file
src/chat-socket/responses.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/responses.c.i
.PHONY : src/chat-socket/responses.c.i

src/chat-socket/responses.s: src/chat-socket/responses.c.s
.PHONY : src/chat-socket/responses.s

# target to generate assembly for a file
src/chat-socket/responses.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/chat-socket/responses.c.s
.PHONY : src/chat-socket/responses.c.s

src/gui_utils.o: src/gui_utils.c.o
.PHONY : src/gui_utils.o

# target to build an object file
src/gui_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/gui_utils.c.o
.PHONY : src/gui_utils.c.o

src/gui_utils.i: src/gui_utils.c.i
.PHONY : src/gui_utils.i

# target to preprocess a source file
src/gui_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/gui_utils.c.i
.PHONY : src/gui_utils.c.i

src/gui_utils.s: src/gui_utils.c.s
.PHONY : src/gui_utils.s

# target to generate assembly for a file
src/gui_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/gui_utils.c.s
.PHONY : src/gui_utils.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/main.c.s
.PHONY : src/main.c.s

src/uchat.o: src/uchat.c.o
.PHONY : src/uchat.o

# target to build an object file
src/uchat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/uchat.c.o
.PHONY : src/uchat.c.o

src/uchat.i: src/uchat.c.i
.PHONY : src/uchat.i

# target to preprocess a source file
src/uchat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/uchat.c.i
.PHONY : src/uchat.c.i

src/uchat.s: src/uchat.c.s
.PHONY : src/uchat.s

# target to generate assembly for a file
src/uchat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/json_c_test.dir/build.make CMakeFiles/json_c_test.dir/src/uchat.c.s
.PHONY : src/uchat.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... json_c_test"
	@echo "... src/chat-socket/array_list_utils.o"
	@echo "... src/chat-socket/array_list_utils.i"
	@echo "... src/chat-socket/array_list_utils.s"
	@echo "... src/chat-socket/chat_socket.o"
	@echo "... src/chat-socket/chat_socket.i"
	@echo "... src/chat-socket/chat_socket.s"
	@echo "... src/chat-socket/requests.o"
	@echo "... src/chat-socket/requests.i"
	@echo "... src/chat-socket/requests.s"
	@echo "... src/chat-socket/responses.o"
	@echo "... src/chat-socket/responses.i"
	@echo "... src/chat-socket/responses.s"
	@echo "... src/gui_utils.o"
	@echo "... src/gui_utils.i"
	@echo "... src/gui_utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/uchat.o"
	@echo "... src/uchat.i"
	@echo "... src/uchat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

